apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-java-web-app-AZ
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=tanzu-java-web-app2'
  links:
    - url: https://docs.google.com/document/d/1HZQiV_VUkmVzjh1CaGcf4DhAXLeFIUeaoUXrARWlgGI/edit
      icon: docs
      title: Plugin Guide
    - url: https://vmware.slack.com/archives/C028W549JHX
      icon: chat
      title: Slack Channel
    - url: http://tanzu-java-web-app.default.jklassen-pstar-dev.calatrava.vmware.com
      title: Website
spec:
  type: service
  lifecycle: experimental
  owner: dream-team-AZ
